# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vote.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import csv

class Ui_MainWindow(object):
    '''
    Class that creates the window and widgets for the GUI.
    '''
    def setupUi(self, MainWindow):
        '''
        Method to set main window properties and to create and place GUI widgets.
        '''
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(390, 390)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(140, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_candidates = QtWidgets.QLabel(self.centralwidget)
        self.label_candidates.setGeometry(QtCore.QRect(10, 40, 251, 141))
        self.label_candidates.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_candidates.setObjectName("label_candidates")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(80, 190, 61, 16))
        self.label_id.setObjectName("label_id")
        self.label_choice = QtWidgets.QLabel(self.centralwidget)
        self.label_choice.setGeometry(QtCore.QRect(10, 220, 131, 16))
        self.label_choice.setObjectName("label_choice")
        self.lineEdit_id = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_id.setGeometry(QtCore.QRect(140, 190, 231, 21))
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.lineEdit_choice = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_choice.setGeometry(QtCore.QRect(140, 220, 231, 21))
        self.lineEdit_choice.setObjectName("lineEdit_choice")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(10, 285, 371, 51))
        self.label_output.setText("")
        self.label_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_output.setObjectName("label_output")
        self.button_submit = QtWidgets.QPushButton(self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(282, 250, 91, 32))
        self.button_submit.setObjectName("button_submit")
        self.label_vote_count = QtWidgets.QLabel(self.centralwidget)
        self.label_vote_count.setGeometry(QtCore.QRect(269, 40, 101, 141))
        self.label_vote_count.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_vote_count.setObjectName("label_vote_count")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 390, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        '''
        Method to translate setupUI and set inital text of labels.
        '''
        output = ''
        votes_output = ''
        with open('candidates.csv', 'r') as csvfile:
            candidates = csv.reader(csvfile)
            candidates_output = 'Candidates:\n\n'
            first = True
            votes_output = 'Total Votes:\n\n'
            for line in candidates:
                if not first:
                    candidates_output += line[0] + ' ' + line[1] + ': ' + line[2] + '\n'
                    votes_output += '0\n'
                else:
                    first = False
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vote"))
        self.label_title.setText(_translate("MainWindow", "Vote Menu"))
        self.label_candidates.setText(_translate("MainWindow", candidates_output))
        self.label_id.setText(_translate("MainWindow", "Enter ID:"))
        self.label_choice.setText(_translate("MainWindow", "Choose a candidate:"))
        self.button_submit.setText(_translate("MainWindow", "SUBMIT"))
        self.label_vote_count.setText(_translate("MainWindow", votes_output))
        self.label_output.setText(_translate("MainWindow", "Enter 8 digit ID."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
